Support arm64 with efi bootloader
snapcore/core18 pull request #116
Opened 2019-01-30 09:29 UTC by woodrow-shen

There is a arm64 system with efi boot and currently it failed to boot
uc18 due to ubuntu-core-rootfs of initramfs lost ${rootmnt}/boot/efi,
where it wasn't created from core18 snap. To consider this case, core18
should make sure /boot/efi can be built with the same hook.

2019-01-30 16:20 UTC, sil2100 requested changes
+1 on the overall changes, just requesting a small stylistic change inline.

I think this is a good approach, especially that we're unconditionally creating /boot/uboot already.

2019-01-30 16:20 UTC, sil2100 commented on hooks/016-ensure-bootloaders.chroot
> -        mkdir /boot/efi
Can we simply remove the amd64|i386 case altogether now? Doesn't make sense to leave an empty case-statement here.

2019-01-31 06:28 UTC, woodrow-shen commented on hooks/016-ensure-bootloaders.chroot
> -        mkdir /boot/efi
@sil2100,
+1, I refreshed my branch again.

2019-02-07 14:28 UTC, sil2100 approved these changes
+1

2019-02-07 14:28 UTC, merged