hooks: fix broken symlink /etc/sysctl.conf.d/99-sysctl.conf
snapcore/core18 pull request #155
Opened 2020-06-16 16:47 UTC by mvo5

Core currently has a symlink /etc/sysctl.conf.d/99-sysctl.conf that
points to /etc/sysctl.conf. This file is removed by the core build
so removing this symlink is also needed.

Note that the sysctl.conf file is not writable on core and it
only contains commented out entries.

2020-06-16 16:52 UTC, pedronis approved these changes
thank you, for context we noticed this issue within the work for https://github.com/snapcore/snapd/pull/8702

2020-07-23 13:59 UTC, xnox approved these changes

2020-07-23 14:00 UTC, xnox requested changes
I think the path is wrong.

Did you mean

```
$ ls -latr /snap/core18/current/etc/sysctl.d/99-sysctl.conf 
lrwxrwxrwx 1 root root 14 Feb  6 15:00 /snap/core18/current/etc/sysctl.d/99-sysctl.conf -> ../sysctl.conf
```

2020-07-23 14:26 UTC, pedronis commented
@xnox your are right, the "conf." bit should not be there

2020-08-11 08:44 UTC, mvo5 commented
Sorry, fixed now.

2020-08-12 16:35 UTC, sil2100 approved these changes
Looks good now indeed.

2020-08-12 16:35 UTC, merged